#!/bin/bash

echo "🧹 Script para Limpar Cache e Testar"
echo "======================================"
echo ""
echo "OPÇÃO 1 - Via ADB (Android conectado):"
echo "---------------------------------------"
echo "adb shell pm clear host.exp.exponent"
echo "adb shell input keyevent 82"
echo ""
echo "OPÇÃO 2 - Via Metro Bundler:"
echo "---------------------------------------"
echo "No terminal do Metro, pressione:"
echo "  r - reload"
echo "  R - full reload"
echo ""
echo "OPÇÃO 3 - Restart completo:"
echo "---------------------------------------"
echo "1. Feche o app completamente"
echo "2. No terminal: npm start -- --reset-cache"
echo "3. Abra o app novamente"
echo ""
echo "OPÇÃO 4 - Desenvolvimento (mais seguro):"
echo "---------------------------------------"
echo "1. Feche o app"
echo "2. Limpe dados do app no celular:"
echo "   Configurações > Apps > Expo Go > Limpar dados"
echo "3. Abra o app novamente"
echo ""
echo "======================================"
echo "✅ Depois de limpar o cache:"
echo "======================================"
echo "1. Abra a tela Agenda"
echo "2. Clique em qualquer agendamento"
echo "3. Clique no botão WhatsApp"
echo "4. Deve abrir instantaneamente!"
echo ""
